#
# This source file is part of the StudyApplication based on the Stanford Spezi Template Application project
#
# SPDX-FileCopyrightText: 2023 Stanford University
#
# SPDX-License-Identifier: MIT
#

name: Beta Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  buildandtest:
    name: Build and Test
    uses: ./.github/workflows/build-and-test.yml
    permissions:
      contents: read
    secrets: inherit
  iosapptestflightdeployment:
    name: iOS App TestFlight Deployment
    needs: buildandtest
    uses: StanfordSpezi/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    permissions:
      contents: read
    with:
      runsonlabels: '["macOS", "self-hosted"]'
      googleserviceinfoplistpath: 'StudyApplication/Supporting Files/GoogleService-Info.plist'
      setupsigning: true
      fastlanelane: beta
    secrets: inherit
  deployfirebase:
    name: Deploy Firebase Project
    needs: iosapptestflightdeployment
    uses: StanfordBDHG/.github/.github/workflows/firebase-deploy.yml@v2
    permissions:
      contents: read
    with:
      arguments: '--debug'
      customcommand: 'npm install --prefix functions'
    secrets:
      GOOGLE_APPLICATION_CREDENTIALS_BASE64: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_BASE64 }}
