#
# This source file is part of the StudyApplication based on the Stanford Spezi Template Application project
#
# SPDX-FileCopyrightText: 2023 Stanford University
#
# SPDX-License-Identifier: MIT
#

name: Build and Test

on:
  pull_request:
  workflow_dispatch:
  workflow_call:

jobs:
  reuse_action:
    name: REUSE Compliance Check
    uses: StanfordBDHG/.github/.github/workflows/reuse.yml@v2
    permissions:
      contents: read
  swiftlint:
    name: SwiftLint
    uses: StanfordBDHG/.github/.github/workflows/swiftlint.yml@v2
    permissions:
      contents: read
  eslint:
    name: eslint
    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
      run:
        working-directory: ./functions
    steps:
      - uses: actions/checkout@v4
      - name: Setup NodeJS
        uses: actions/setup-node@v3
      - name: eslint
        run: |
          npm install
          npm run lint
  markdownlinkcheck:
    name: Markdown Link Check
    uses: StanfordBDHG/.github/.github/workflows/markdown-link-check.yml@v2
    permissions:
      contents: read
  buildandtest:
    name: Build and Test
    uses: StanfordSpezi/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    permissions:
      contents: read
    with:
      artifactname: StudyApplication.xcresult
      runsonlabels: '["macOS", "self-hosted"]'
      setupSimulators: true
      setupfirebaseemulator: true
      customcommand: "npm install --prefix ./functions && firebase emulators:exec 'fastlane test'"
  uploadcoveragereport:
    name: Upload Coverage Report
    needs: buildandtest
    uses: StanfordBDHG/.github/.github/workflows/create-and-upload-coverage-report.yml@v2
    permissions:
      contents: read
    with:
      coveragereports: StudyApplication.xcresult
    secrets:
      token: ${{ secrets.CODECOV_TOKEN }}
